// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM2lHXCO8VlNcVBfH1jxyULN4o6xHOg7Q',
    appId: '1:936156779130:web:57c1e76bf69243ebad21c3',
    messagingSenderId: '936156779130',
    projectId: 'waiterorderapp-2969d',
    authDomain: 'waiterorderapp-2969d.firebaseapp.com',
    storageBucket: 'waiterorderapp-2969d.appspot.com',
    measurementId: 'G-YSPVHCC8B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJOlCZvYKliQVCjBakC8gyo7MFySoUkKc',
    appId: '1:936156779130:android:0f68d8591dc2f217ad21c3',
    messagingSenderId: '936156779130',
    projectId: 'waiterorderapp-2969d',
    storageBucket: 'waiterorderapp-2969d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-aaUPzSgfs54NZ8uPPxZlFOthNrP4hpg',
    appId: '1:936156779130:ios:28eaa4561e46008dad21c3',
    messagingSenderId: '936156779130',
    projectId: 'waiterorderapp-2969d',
    storageBucket: 'waiterorderapp-2969d.appspot.com',
    iosBundleId: 'com.example.waiterOrderAppLv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-aaUPzSgfs54NZ8uPPxZlFOthNrP4hpg',
    appId: '1:936156779130:ios:a449a21617ebd32aad21c3',
    messagingSenderId: '936156779130',
    projectId: 'waiterorderapp-2969d',
    storageBucket: 'waiterorderapp-2969d.appspot.com',
    iosBundleId: 'com.example.waiterOrderAppLv.RunnerTests',
  );
}
